org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.75

## Mod Properties
mod_id=harvestheritage
mod_name=HarvestHeritage
mod_license=MIT
mod_version=1.3.2
mod_group_id=me.theabab2333.harvestheritage
